import subprocess
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent
MAIN = ROOT / "main"


class MainIntegrationTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        subprocess.run(["make", "main"], cwd=ROOT, check=True)

    def run_main(self, input_data):
        return subprocess.run(
            [str(MAIN)],
            input=input_data,
            text=True,
            capture_output=True,
            cwd=ROOT,
            check=False,
        )

    def test_main_executes_basic_graph_commands(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "EDGE A B 7",
                    "REMOVE EDGE A B",
                    "REMOVE NODE A",
                    "RPO_NUMBERING B",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "B \n")

    def test_main_stops_on_invalid_instruction(self):
        proc = self.run_main("BOGUS\n")

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "")

    def test_main_large_autogenerated_dag(self):
        node_count = 64
        nodes = [f"N{i}" for i in range(node_count)]
        edges = []

        for i in range(node_count - 1):
            edges.append((nodes[i], nodes[i + 1], i + 1))
        for step in (2, 5):
            for i in range(node_count - step):
                edges.append((nodes[i], nodes[i + step], 1000 + step * 100 + i))

        commands = [f"NODE {node}" for node in nodes]
        commands.extend(f"EDGE {src} {dst} {weight}" for src, dst, weight in edges)
        commands.append("RPO_NUMBERING N0")

        proc = self.run_main("\n".join(commands) + "\n")

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, " ".join(nodes) + " \n")

    def test_main_large_autogenerated_cyclic_graphs(self):
        for prefix, node_count, back_step in (("C", 96, 11), ("D", 128, 17)):
            with self.subTest(prefix=prefix, node_count=node_count, back_step=back_step):
                nodes = [f"{prefix}{i}" for i in range(node_count)]
                chain_edges = [
                    (nodes[i], nodes[i + 1], i + 1)
                    for i in range(node_count - 1)
                ]
                back_edges = [
                    (nodes[i], nodes[i - back_step], 10000 + i)
                    for i in range(back_step, node_count, back_step)
                ]

                commands = [f"NODE {node}" for node in nodes]
                commands.extend(
                    f"EDGE {src} {dst} {weight}"
                    for src, dst, weight in chain_edges + back_edges
                )
                commands.append(f"RPO_NUMBERING {nodes[0]}")

                proc = self.run_main("\n".join(commands) + "\n")

                expected_stdout = "".join(
                    f"Found loop {src}->{dst}\n" for src, dst, _ in back_edges
                )
                expected_stdout += " ".join(nodes) + " \n"

                self.assertEqual(proc.returncode, 0)
                self.assertEqual(proc.stdout, expected_stdout)

    def test_main_dijkstra_sample(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "EDGE A B 10",
                    "EDGE B C 10",
                    "EDGE C D 10",
                    "DIJKSTRA A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "B 10\nC 20\nD 30\n")

    def test_main_dijkstra_complex_weighted_graph(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE E",
                    "NODE F",
                    "NODE G",
                    "NODE H",
                    "EDGE A B 4",
                    "EDGE A C 2",
                    "EDGE B C 5",
                    "EDGE B D 10",
                    "EDGE C E 3",
                    "EDGE E D 4",
                    "EDGE D F 11",
                    "EDGE E F 2",
                    "EDGE C G 20",
                    "EDGE G H 1",
                    "DIJKSTRA A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(
            proc.stdout,
            "".join(
                [
                    "B 4\n",
                    "C 2\n",
                    "D 9\n",
                    "E 5\n",
                    "F 7\n",
                    "G 22\n",
                    "H 23\n",
                ]
            ),
        )

    def test_main_dijkstra_skips_unreachable_nodes(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE E",
                    "EDGE A B 1",
                    "EDGE B C 2",
                    "EDGE D E 3",
                    "DIJKSTRA A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "B 1\nC 3\n")

    def test_remove_edge_then_dijkstra_rpo_and_repeat_remove(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "EDGE A B 1",
                    "EDGE B C 2",
                    "EDGE C D 3",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "REMOVE EDGE B C",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "REMOVE EDGE B C",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(
            proc.stdout,
            "".join(
                [
                    "B 1\n",
                    "C 3\n",
                    "D 6\n",
                    "A B C D \n",
                    "B 1\n",
                    "A B \n",
                    "B 1\n",
                    "A B \n",
                ]
            ),
        )

    def test_remove_node_then_dijkstra_rpo_and_repeat_remove(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "EDGE A B 1",
                    "EDGE B C 2",
                    "EDGE C D 3",
                    "EDGE A D 10",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "REMOVE NODE C",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "REMOVE NODE C",
                    "DIJKSTRA A",
                    "RPO_NUMBERING A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(
            proc.stdout,
            "".join(
                [
                    "B 1\n",
                    "C 3\n",
                    "D 6\n",
                    "A B C D \n",
                    "B 1\n",
                    "D 10\n",
                    "A D B \n",
                    "Unknown node C\n",
                    "B 1\n",
                    "D 10\n",
                    "A D B \n",
                ]
            ),
        )

    def test_main_maxflow_sample(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE G",
                    "EDGE A B 3",
                    "EDGE A C 2",
                    "EDGE B C 1",
                    "EDGE B D 2",
                    "EDGE C D 4",
                    "EDGE C G 2",
                    "EDGE D G 3",
                    "MAXFLOW A G",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "5\n")

    def test_main_maxflow_complex_residual_network(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE S",
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE T",
                    "EDGE S A 16",
                    "EDGE S C 13",
                    "EDGE A B 12",
                    "EDGE B C 9",
                    "EDGE C A 4",
                    "EDGE C D 14",
                    "EDGE D B 7",
                    "EDGE B T 20",
                    "EDGE D T 4",
                    "MAXFLOW S T",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "23\n")

    def test_main_maxflow_sums_parallel_edges(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE S",
                    "NODE A",
                    "NODE B",
                    "NODE T",
                    "EDGE S A 5",
                    "EDGE S A 7",
                    "EDGE A T 10",
                    "EDGE S B 4",
                    "EDGE B T 4",
                    "MAXFLOW S T",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "14\n")

    def test_main_tarjan_sample(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "EDGE A B 1",
                    "EDGE B C 1",
                    "EDGE C A 1",
                    "TARJAN A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "A B C \n")

    def test_main_tarjan_multiple_components_from_start(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE E",
                    "NODE F",
                    "NODE G",
                    "NODE H",
                    "NODE I",
                    "NODE J",
                    "NODE K",
                    "EDGE A B 1",
                    "EDGE B C 1",
                    "EDGE C A 1",
                    "EDGE C D 1",
                    "EDGE D E 1",
                    "EDGE E D 1",
                    "EDGE E F 1",
                    "EDGE F G 1",
                    "EDGE G H 1",
                    "EDGE H F 1",
                    "EDGE H I 1",
                    "EDGE I J 1",
                    "EDGE J K 1",
                    "EDGE K I 1",
                    "TARJAN A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(
            proc.stdout,
            "".join(
                [
                    "I J K \n",
                    "F G H \n",
                    "D E \n",
                    "A B C \n",
                ]
            ),
        )

    def test_main_tarjan_ignores_singleton_components(self):
        proc = self.run_main(
            "\n".join(
                [
                    "NODE A",
                    "NODE B",
                    "NODE C",
                    "NODE D",
                    "NODE E",
                    "EDGE A B 1",
                    "EDGE B C 1",
                    "EDGE C B 1",
                    "EDGE C D 1",
                    "EDGE D E 1",
                    "TARJAN A",
                    "",
                ]
            )
        )

        self.assertEqual(proc.returncode, 0)
        self.assertEqual(proc.stdout, "B C \n")


if __name__ == "__main__":
    unittest.main()
